{% set name = "jbpy" %}
{% set version = "0.5.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jbpy-{{ version }}.tar.gz
  sha256: ac77bfcbddcd3d8fa1633db627a0ab2c74d89d7bd89f48aed9865553b7354624

build:
  entry_points:
    - jbpinfo = jbpy._jbpinfo:main
    - jbpdump = jbpy._jbpdump:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - jbpy
  commands:
    - pip check
    - jbpinfo --help
    - jbpdump --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ValkyrieSystems/jbpy
  summary: Library for reading and writing Joint BIIF Profile (JBP) files (NITF and NSIF)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pressler-vsc
    - bombaci-vsc
    - johnstob
